#!/bin/env python3
#  Copyright (c) 2023.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

import argparse
import socket

PIPE = "/var/run/pwm_pipe"


def send_value(duty: int) -> None:
	"""
	Send the value to the PWM pipe
	:param duty: pwm duty cycle between 0 and 100
	"""
	client = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
	try:
		client.connect(PIPE)
		client.sendall(str(duty).encode('utf-8'))
	finally:
		client.close()


if __name__ == "__main__":
	parser = argparse.ArgumentParser()
	parser.add_argument("duty", type=int, choices=range(0, 101), default=75, help="Duty cycle")
	args = parser.parse_args()

	try:
		value = args.duty
		send_value(value)
		print(f"Setting new duty: {value}")
	except ValueError:
		print("Please enter a valid integer!")
